PROJECTS = [
  {
    "title": 'Personal Portfolio Website',
    "description": "A modern, responsive Vue.js portfolio built with PrimeVue components, featuring automated testing with Cypress and Playwright.",
    "technologies": ["Vue.js", "PrimeVue", "Vite", "Cypress", "Playwright"],
    "skillsLeveraged": [
      "Frontend Development",
      "Component Architecture",
      "Automated Testing",
      "Responsive Design",
      "Git Version Control",
      "CI/CD Pipeline",
      "AI Agentic Development"
    ],
    "status": 'In Development',
    "github": 'https://github.com/jakekohl/jakekohl.github.io',
    "demo": 'https://jakekohl.github.io',
    "features": [
      "Responsive design with professional styling",
      "Component-based architecture",
      "Automated testing setup",
      "GitHub Pages deployment",
    ],
    "dataTest": 'project-portfolio',
    "images": [],
  },
  {
    "title": 'Calculator',
    "description": "A simple calculator program built with tinker and pytest",
    "technologies": ["Python", "Tinker", "Pytest"],
    "skillsLeveraged": [
      "Object-Oriented Programming",
      "Unit Testing",
      "Debugging",
    ],
    "status": 'In Development',
    "github": "https://github.com/jakekohl/calculator-project",
    "features": [
      "Simple calculator interface",
      "Basic arithmetic operations",
      "Unit testing with pytest",
      "CI/CD Pipeline using GitHub Actions"
    ],
    "dataTest": "project-calculator",
    "images": [],
  },
  {
    "title": 'Nurtured Heart AI',
    "description": "A web service that generates heartfelt, meaningful compliments using the Nurtured Heart Approach. Features local LLM processing with Ollama and a beautiful Vue.js frontend.",
    "technologies": ["Vue.js", "Python", "FastAPI", "Ollama", "PrimeVue", "Vite", "Google Gemini", "Docker"],
    "skillsLeveraged": [
      "Full-Stack Development",
      "Local LLM Integration",
      "API Design & Development",
      "Vue.js Development",
      "Python Backend Development",
      "AI/ML Application Architecture",
      "Prompt Engineering",
      "Docker Containerization",
      "Responsive UI Design",
      "Google Gemini API Integration",
      "Cypress End-to-End Testing",
      "CI/CD Pipeline using GitHub Actions",
    ],
    "status": 'In Development',
    "github": "https://github.com/jakekohl/nurtured-heart-ai",
    "demo": "https://nha.jakekohl.dev",
    "features": [
      "Local LLM-powered compliment generation with Ollama",
      "Nurtured Heart Approach methodology integration",
      "FastAPI backend with real-time processing",
      "Beautiful Vue.js + PrimeVue frontend",
      "Personalized compliments with context and tone options",
      "Containerized deployment with Docker",
    ],
    "dataTest": "project-nurtured-heart-ai",
    "images": [],
  },
]